### ISSUE TITLE
TravisCIで実行するRubyのバージョンについて

### ISSUE THREAD

**Issue by toshihirock** [kentaro/fluent-plugin-conditional_filter#2]
PullRequestをさせて頂きたい箇所があり、最新の状態でTravisCIでRspecを実行させてみたのですが、以下3点が原因でエラーとなってしまいました。

[TravisCI-error](https://travis-ci.org/toshihirock/fluent-plugin-conditional_filter/builds/56342256)

 1. テスト実行前にFluent::Test.setupが呼ばれていない事が原因によるエラー
 1. Ruby1.9.2での実行時に依存しているgemのstring-scrubがRuby1.9.3以上を要求するようになった事によるエラー
 1. Ruby-head(2.3.0dev)だとtest/unitがバンドルされていない事が原因と思われるエラー

1点目についてはテスト実行前にFluent::Test.setupを呼ぶようにすることで解決することができました。

2点目、3点目についてなのですが、flunetdのv2は2.1.*,v1は1.9.3を利用しているようなので

+ Ruby1.9.2でのビルドはしないようにする
+ Ruby-headはRuby-2.1.*に置き換える

などすることも検討しても良いかと思ったのですが、どうでしょうか。

なお、上記変更を行うことでテストがパスすることまでは確認ができました。

[TravisCI-pass](https://travis-ci.org/toshihirock/fluent-plugin-conditional_filter/builds/56347813)

**Comment by kentaro** [comment]
Looks Goodと思いますので、プルリクいただけると幸いです！
